settings:
  bulk: true
  defaultSet: 300000
  databases:
    - name: postgres
      tables:
        - name: test0
          set: 100000
          #typeSettings: ["character varying length = 10"]


#  databases:
#      - name: test_database
#        tables:
#          - name: test
#            rules: [ "$unique", "$full-unique", "$positive" ]
#            column:
#              - name:
#                rules: [
#                  "$value < 10",
#                  "$annotation=tableName.columnName",
#                  "$dictionary=ИмяСправочника"
#             ]


# Вынести сюда все правила факера