settings:
  separator: "//"
  dictionaryFolder: "./dictionary"
  connections:
    - name: testDatabase
      connection:
        host: "localhost"
        port: "5432"
        user: "postgres"
        password: "postgres"
        dbname: "postgres"
        sslMode: "disable"
        schema: "public"
  blackListPath: [
    "testDatabase//test_database//typeorm_metadata",
    "testDatabase//test_database//user_migrations",
    "testDatabase//test_database//migration",
  ]
  defaultSet: 100
  defaultTypeSettings:
    varcharLength: 10
    numericRange:
      in: 0
      out: 10
  databases:
    - name: postgres
      tables:
        - name: case1
          set: 10
          columns:
            - name: name
              settings:
                range:
                  in: "2022-01-01"
                unique: true
                dictionary: names
                #annotation: connectionName_database_schema_table_column
