settings:
  bulk: true
  defaultSet: 30
  databases:
    - name: test_database
      tables:
        - name: test
          set: 10000000


#  databases:
#      - name: test_database
#        tables:
#          - name: test
#            rules: [ "$unique", "$full-unique", "$positive" ]
#            column:
#              - name:
#                rules: [
#                  "$value < 10",
#                  "$annotation=tableName.columnName",
#                  "$dictionary=ИмяСправочника"
#             ]


# Вынести сюда все правила факера