settings:
  defaultSet: 10000
  types:
    varcharDefaultLength: 10
  databases:
    - name: postgres
          #typeSettings: ["character varying length = 10"]

# billing
#  databases:
#      - name: test_database
#        tables:
#          - name: test
#            rules: [ "$unique", "$full-unique", "$positive" ]
#            column:
#              - name:
#                rules: [
#                  "$value < 10",
#                  "$annotation=tableName.columnName",
#                  "$dictionary=ИмяСправочника"
#             ]


# Вынести сюда все правила факера