settings:
  connections:
    - name: postgres
      connection: "host=localhost port=5432 user=postgres dbname=postgres password=postgres sslmode=disable"
  blackListPath: [
    #connectionName_database_schema_table
    "database_table_"
  ]
  defaultSet: 100
  types:
    varcharDefaultLength: 10
  databases:
    - name: test_database
          #typeSettings: ["character varying length = 10"]

# billing
#  databases:
#      - name: test_database
#        tables:
#          - name: test
#            rules: [ "$unique", "$full-unique", "$positive" ]
#            column:
#              - name:
#                rules: [
#                  "$value < 10",
#                  "$annotation=tableName.columnName",
#                  "$dictionary=ИмяСправочника"
#             ]


# Вынести сюда все правила факера